Repository aliyun/plugsched, pull requests merged in 2022-12, with the labels that each got.

#154 Fix stack trace
  src/stack_check.h
Labels: anolis_testing

#167 border: fix sched_class renaming failing on some kernels
  boundary/extract.py
Labels: anolis_test_pass

#168 tests: fix building in container
  tests/build_case
Labels: anolis_test_pass

#169 src: fix a typo of FIELD_TYPE
  src/mempool.h
Labels: anolis_testing

#170 border: fix an inaccurate replacement about static __used
  boundary/extract.py
Labels: anolis_test_fail

#172 config: fix panic when CPU hotplug on 5.10
  configs/5.10/boundary.yaml
Labels: anolis_test_fail

#171 border: exclude not-linked weak functions from tainted functions
  boundary/analyze.py
Labels: anolis_test_pass

#173 config: fix stack pivot, stack chk and springboard for 5.10 on aarch64
  configs/5.10/dynamic_springboard.patch
  tools/springboard_search.sh
Labels: anolis_test_fail

#178 border: update post_extract.patch of 3.10
  configs/3.10/post_extract.patch
Labels: anolis_testing
