Repository aliyun/plugsched, pull requests merged in 2022-08, with the labels that each got.

#94 border: try to remove inside callback functions out of fn_ptr set
  boundary/analyze.py
  boundary/collect.py
  configs/4.19/boundary.yaml
  configs/5.10/boundary.yaml
  src/sched_rebuild.c
Labels: anolis_testing

#100 src: change the term fnptr to callback
  boundary/analyze.py
  boundary/collect.py
  boundary/extract.py
  src/Makefile
  src/head_jump.h
  src/stack_check.h
  tools/symbol_resolve/symbol_resolve.cpp
Labels: anolis_test_fail

#99 border: forbid redirecting mangled functions
  boundary/analyze.py
Labels: anolis_test_fail

#98 tests: add a reboot test
  tests/bundles/reboot
  tests/test_reboot/assert
  tests/test_reboot/patch.diff
  tests/test_reboot/runonce
Labels: anolis_test_fail

#101 Reduce gcc callback
  boundary/collect.py
  boundary/extract.py
  cli.py
Labels: anolis_testing

#105 border: fix "forbid redirecting mangled functions"
  boundary/analyze.py
Labels: anolis_testing

#106 src: fix kernel panic when loading scheduler.ko
  src/sched_rebuild.c
Labels: anolis_testing

#111 cli: print logging to stdio for better user experience
  cli.py
Labels: anolis_test_fail

#107 src: fix kernel panic during cpu hotplug test
  src/main.c
  src/sched_rebuild.c
Labels: anolis_testing

#103 border: fix accessing union bug
  boundary/collect.py
Labels: anolis_test_fail

#113 Revert "cli: put off copying the vmlinux and Module.symver files"
  cli.py
Labels: anolis_testing

#116 tools: fix stackprotector search for aarch64
  tools/springboard_search.sh
Labels: anolis_test_pass

#112 PEP8 code style for extract.py
  boundary/extract.py
Labels: anolis_test_fail

#120 Fix two symbol issues
  boundary/analyze.py
Labels: anolis_test_pass

#123 border: fix accessing unnamed struct bug
  boundary/collect.py
Labels: anolis_testing

#121 delete EXPORT_SYMBOL for header & sidecar files
  cli.py
Labels: anolis_test_pass, anolis_test_fail

#117 border: forbid redirecting mangled functions
  boundary/analyze.py
Labels: anolis_test_pass

#102 fix some bugs of plugsched service
  module-contrib/plugsched.service
  module-contrib/scheduler-installer
  module-contrib/scheduler.spec
Labels: anolis_test_pass

#126 two patch to improve code readability
  README.md
  README_zh.md
  boundary/collect.py
  boundary/extract.py
Labels: anolis_test_pass

#127 Fix sidecar
  boundary/analyze.py
  boundary/collect.py
  boundary/extract.py
Labels: anolis_test_pass

#128 border: delete generated intermediate file 'interface_callbacks'
  boundary/analyze.py
  src/Makefile
Labels: anolis_test_fail

#132 border: delete __init function in unused macro branches to improve re…
  boundary/extract.py
Labels: anolis_test_pass

#131 Fix static variable access error
  boundary/extract.py
  configs/4.19/post_extract.patch
  configs/5.10/post_extract.patch
  src/Makefile
  src/head_jump.h
  src/main.c
  src/scheduler.lds
  src/stack_check.h
Labels: anolis_test_pass

#124 PEP8 code style for analyze.py
  boundary/analyze.py
  boundary/extract.py
Labels: anolis_test_pass

#133 src: fix invalid symbol reference when using __mod_ prefix
  src/Makefile
Labels: anolis_test_fail

#134 boundary: Prevent static interface functions from being optimized
  boundary/extract.py
  configs/4.19/dynamic_springboard.patch
Labels: anolis_testing

#139 doc: update documentation for new sidecar implementation
  docs/Advanced-Features.md
Labels: anolis_test_fail

#143 tools: fix stack protector search
  tools/springboard_search.sh
Labels: anolis_test_pass
