Repository aliyun/plugsched, pull requests merged in 2022-11, with the labels that each got.

#164 Fix the compiling error of modification of sched_class on arm64
  src/head_jump.h
  src/helper.h
  src/main.c
  src/sched_rebuild.c
  src/stack_check.h
Labels: anolis_test_pass

#162 Remove the assert of sched_class
  boundary/analyze.py
Labels: anolis_test_pass

#165 Adjust the boundary of 5.10.
  configs/5.10/boundary.yaml
Labels: anolis_test_pass

#163 Support kernel v3.10 on CentOS 7.9 on x86_64
  configs/3.10/boundary.yaml
  configs/3.10/dynamic_springboard.patch
  configs/3.10/post_extract.patch
  configs/3.10/pre_extract.patch
Labels: anolis_testing

#151 border: fix "keep only one if both strong and weak symbol exist"
  boundary/analyze.py
  boundary/collect.py
  src/Makefile.plugsched
Labels: anolis_test_fail

#166 Update the dynamic_springboard.patch of 5.10.
  configs/5.10/dynamic_springboard.patch
  src/Makefile
  src/main.c
  tools/springboard_search.sh
Labels: anolis_test_pass
