Repository aliyun/plugsched, pull requests merged in 2023-03, with the labels that each got.

#190 contrib: fix unmatching version of gcc and gcc-python-plugin in Docke…
  Dockerfile.x86_64
Labels: anolis_test_fail

#193 src: use the right rule to reference symbols in module
  src/Makefile
  src/main.c
  src/sched_rebuild.c
Labels: anolis_test_fail

#189 fix several bugs
  boundary/collect.py
  boundary/extract.py
  cli.py
  configs/3.10/pre_extract.patch
  module-contrib/hotfix_conflict_check
  src/Makefile
Labels: anolis_test_fail

#191 Fix somes doc
  ChangeLog.md
  Dockerfile.aarch64
  Dockerfile.x86_64
  NOTICE
  configs/3.10/post_extract.patch
  configs/5.10/post_extract.patch
  tests/test_bare_performance/assert
  tests/test_mem_pressure/assert
  tests/test_reboot/assert
  tests/test_reboot/runonce
  tools/compile_and_create_rpm.sh
Labels: anolis_test_pass

#194 Set the default value for the any new added configs.
  cli.py
Labels: anolis_test_pass

#186 Fix sdcr interface
  boundary/collect.py
  boundary/extract.py
Labels: anolis_test_fail

#195 Fix some problems of libraries of python and unify the Dockerfile of x86 and arm64
  Dockerfile
  Dockerfile.aarch64
  cli.py
  tests/prep_env
  tests/test_bare_performance/assert
  tests/test_cpu_throttle/assert
  tests/test_mem_pressure/assert
  tests/test_reboot/assert
  tests/test_sched_syscall/assert
  tools/yaml-diff.py
Labels: anolis_testing

#196 Standardized spec of scheduler package.
  README.md
  README_zh.md
  cli.py
  module-contrib/scheduler.spec
  tests/build_case
Labels: anolis_testing
